name: KinD e2e tests

on:
  push:
    branches: [ 'try-outputs' ]

jobs:

  ko-resolve:
    name: e2e tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        kind-version:
        - v0.7.0 # Defaults to 1.17
        - v0.8.1 # Defaults to 1.18
        - v0.9.0 # Defaults to 1.19

        test-suite:
        - ./test/conformance/runtime
        - ./test/conformance/api/v1alpha1
        - ./test/conformance/api/v1beta1
        - ./test/conformance/api/v1
        - ./test/e2e

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      KO_DOCKER_REPO: kind.local

    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: ./src/knative.dev/serving

    - name: Step 1
      working-directory: ./src/knative.dev/serving
      run: |
        export FOO1=asdfasdf

        echo "::set-env name=FOO2::asdfasdf"

        echo "::set-output name=foo::bar"

    - name: Step 2
      working-directory: ./src/knative.dev/serving
      run: |
        echo $FOO1
        echo $FOO2

        echo ${{ steps.step1.outputs.foo }}
